### ISSUE TITLE
Suggestion : Root Path

### ISSUE THREAD

**Issue by AEK-BKF** [skyronic/laravel-cookie#8]
Hi,
I think it's useful to put a parameter in config file in order to set the root path.
Actually you set it fixed : App.

Thanks

**Comment by skyronic** [comment]
Thanks for the suggestion! I'll see if it's possible without too much effort since I'm a little busy with work.

What kind of paths/use cases did you have in mind?

**Comment by AEK-BKF** [comment]
Thanks for quick answer !
It's just the project root path '/'
So you can create any file in any folder into the project folder

**Comment by AEK-BKF** [comment]
Hi, Any update ? :)

**Comment by skyronic** [comment]
Hey I spent some time trying to get this started, and turns out it's already possible, I had totally forgotten this feature existed:

https://github.com/skyronic/laravel-file-generator#getting-a-namespace-from-path

If you want to have a file that goes to "custom/MyClass.php", which lives in `CustomNamespace` simply do this:

`php artisan generate:new php__custom`

This will create a file `resources/boilerplates/php__custom.boilerplate.txt`

I've set up the file like this:

```
{
   "name": "My custom template",
   "out": "custom/{{ $name }}.php",
   "params": {
   }
}
---

<?php

namespace {{ Format::getNamespace($path, "custom", "CustomNamespace") }};

class {{ Format::baseName($name) }} {
    public function __construct () {

    }
}
```

Running `php artisan generate php:custom MyClass` gives you:

```
<?php

namespace CustomNamespace;

class MyClass {
    public function __construct () {

    }
}
```

You should be able to make it work with most scenarios by tweaking the `formatNamespace` function call. Hopefully this solves your issue. Please feel free to re-open issue if you still have problems.

**Comment by AEK-BKF** [comment]
Thank you so much :)))))
